name: enhanced_preferences
description: "Wraps platform-specific persistent storage for simple data."
version: 0.3.1
repository: https://github.com/kumo01GitHub/enhanced_preferences

environment:
  sdk: ^3.9.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  plugin:
    platforms:
      android:
        package: io.kumo01.enhanced_preferences
        pluginClass: EnhancedPreferencesPlugin
      ios:
        pluginClass: EnhancedPreferencesPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: EnhancedPreferencesPlugin
        sharedDarwinSource: true
      web:
        pluginClass: EnhancedPreferencesWeb
        fileName: enhanced_preferences_web.dart
