name: Android Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  WORKING_DIRECTORY: example

jobs:
  integration-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter Version
        run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: Run integration test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          disable-spellchecker: true
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: flutter test integration_test
