name: macOS Test

on:
  push:
    paths-ignore:
      - "**.md"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - "**.md"
      - "LICENSE"

permissions:
  contents: read

env:
  WORKING_DIRECTORY: example

jobs:
  integration-test:
    runs-on: macos-${{ matrix.os-version }}
    timeout-minutes: 60
    strategy:
      matrix:
        os-version: [26, 15, 14, 13]
        package-manager: [cocoapods, swiftpm]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e
        with:
          channel: stable
          cache: true

      - name: Flutter Version
        run: flutter doctor -v

      - name: Install Dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: flutter pub get

      - name: Set Package Manager Configuration
        run: |
          if [ "${{ matrix.package-manager }}" == "swiftpm" ]; then
            flutter config --enable-swift-package-manager
          else
            flutter config --no-enable-swift-package-manager
          fi

      - name: Run Integration Tests
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: flutter test integration_test -d macos --ignore-timeouts

      - name: CocoaPods Lint
        if: matrix.package-manager == 'cocoapods'
        run: |
          pod lib lint darwin/enhanced_preferences.podspec --allow-warnings --verbose
